# Generated by Django 6.0.2 on 2026-02-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
